server:
  port: 8102

#logging:
#  level:
#    io.seata.samples.integration: DEBUG
#====================================MySQL=============================================
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.129:3336/seata2?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: yuwenbo
    password: yuwenbo
  application:
    name: business-order-service

#====================================mybatis config===============================================
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#====================================Dubbo config===============================================
dubbo:
  application:
    id: business-order-service
    name: business-order-service
    qosEnable: false
  protocol:
    id: dubbo
    name: dubbo
    port: 20882
  registry:
    id: business-order-service
    address: zookeeper://192.168.3.129:2181,192.168.3.129:2182,192.168.3.129:2183
  config-center:
    address: zookeeper://192.168.3.129:2181,192.168.3.129:2182,192.168.3.129:2183
  metadata-report:
    address: zookeeper://192.168.3.129:2181,192.168.3.129:2182,192.168.3.129:2183
  scan:
    base-packages: io.seata.samples.integration.business
  consumer:
    check: false
    timeout: 2000

#====================================Seata Config===============================================
seata:
  enabled: true
  application-id: business-order-service
  # 参考：https://seata.io/zh-cn/docs/user/configurations.html 附录1
  tx-service-group: my_test_tx_group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  service:
    vgroup-mapping:
      # apollo中要配置相同的值，例如这里就要在apollo的namespace中添加一个配置：key为service.vgroupMapping.my_test_tx_group，value为default
      my_test_tx_group: default # TC 集群（必须与seata-server保持一致）
  config:
    # support: nacos, consul, apollo, zk, etcd3
    type: apollo
    apollo:
      # FAT环境
      # 跳过apollo-meta
      apollo-config-service: http://192.168.3.129:18081
      #apollo-meta: http://192.168.3.129:18081
      app-id: seata-server
      namespace: application
      apollo-accesskey-secret: ""
  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    type: zk
    zk:
      server-addr: 192.168.3.129:2181,192.168.3.129:2182,192.168.3.129:2183

