server:
  port: 8111

#====================================Dubbo config===============================================
dubbo:
  application:
    id: business-seata-tcc
    name: business-seata-tcc
    qosEnable: false
  protocol:
    id: dubbo
    name: dubbo
    port: 20891
  registry:
    id: business-seata-tcc
    address: zookeeper://192.168.3.129:2181,192.168.3.129:2182,192.168.3.129:2183
  config-center:
    address: zookeeper://192.168.3.129:2181,192.168.3.129:2182,192.168.3.129:2183
  metadata-report:
    address: zookeeper://192.168.3.129:2181,192.168.3.129:2182,192.168.3.129:2183
  scan:
    base-packages: io.seata.samples.integration.business
  consumer:
    check: false
    timeout: 2000

#====================================Seata Config===============================================
seata:
  enabled: true
  application-id: business-seata-tcc
  # 参考：https://seata.io/zh-cn/docs/user/configurations.html 附录1
  tx-service-group: my_test_tx_group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  service:
    vgroup-mapping:
      # apollo中要配置相同的值，例如这里就要在apollo的namespace中添加一个配置：key为service.vgroupMapping.my_test_tx_group，value为default
      my_test_tx_group: default # TC 集群（必须与seata-server保持一致）
  config:
    # support: nacos, consul, apollo, zk, etcd3
    type: apollo
    apollo:
      # FAT环境
      # 跳过apollo-meta
      apollo-config-service: http://192.168.3.129:18081
      #apollo-meta: http://192.168.3.129:18081
      app-id: seata-server
      namespace: application
      apollo-accesskey-secret: ""
  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    type: zk
    zk:
      server-addr: 192.168.3.129:2181,192.168.3.129:2182,192.168.3.129:2183
