server:
  port: 8101
#====================================MySQL=============================================
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.129:3326/seata1?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: yuwenbo
    password: yuwenbo
  application:
    name: business-account-service

#====================================mybatis config===============================================
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: io.seata.samples.integration.**.bean
  configuration:
    map-underscore-to-camel-case: true

#====================================Dubbo config===============================================
dubbo:
  application:
    id: business-account-service
    name: business-account-service
    qosEnable: false
  protocol:
    id: dubbo
    name: dubbo
    port: 20881
  registry:
    id: business-account-service
    address: zookeeper://192.168.3.129:2181,192.168.3.129:2182,192.168.3.129:2183
  config-center:
    address: zookeeper://192.168.3.129:2181,192.168.3.129:2182,192.168.3.129:2183
  metadata-report:
    address: zookeeper://192.168.3.129:2181,192.168.3.129:2182,192.168.3.129:2183
  scan:
    base-packages: io.seata.samples.integration.business
  consumer:
    check: false
    timeout: 2000

#====================================Seata Config===============================================
seata:
  enabled: true
  application-id: business-account-service
  # 参考：https://seata.io/zh-cn/docs/user/configurations.html 附录1
  tx-service-group: my_test_tx_group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  client:
    rm:
      lock:
        retry-interval: 10 # 校验或占用全局锁重试间隔（默认10ms）
        retry-times: 30 # 校验或占用全局锁重试次数（默认30）
        retry-policy-branch-rollback-on-conflict: true # 分支事务与其它全局回滚事务冲突时锁策略（优先释放本地锁让回滚成功）
      report-success-enable: true
      table-meta-check-enable: false # 自动刷新缓存中的表结构（默认false）
      report-retry-count: 5 # 一阶段结果上报TC重试次数（默认5）
      async-commit-buffer-limit: 10000 # 异步提交缓存队列长度（默认10000）
    tm:
      commit-retry-count: 3 # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
      rollback-retry-count: 3 # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）
    undo:
      data-validation: true # 二阶段回滚镜像校验（默认true开启）
      log-serialization: jackson # undo序列化方式（默认jackson）
      # SEATA AT 模式需要 UNDO_LOG 表，建表语句在seata项目script/client/at/db/目录下
      # 每个业务数据库都要添加这个表
      log-table: undo_log  # 自定义undo表名（默认undo_log）
  service:
    vgroup-mapping:
      # apollo中要配置相同的值，例如这里就要在apollo的namespace中添加一个配置：key为service.vgroupMapping.my_test_tx_group，value为default
      my_test_tx_group: default # TC 集群（必须与seata-server保持一致）
    enable-degrade: false # 降级开关
    disable-global-transaction: false # 禁用全局事务（默认false）
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true # 客户端事务消息请求是否批量合并发送（默认true）
  config:
    # support: nacos, consul, apollo, zk, etcd3
    type: apollo
    apollo:
      # FAT环境
      # 跳过apollo-meta
      apollo-config-service: http://192.168.3.129:18081
      #apollo-meta: http://192.168.3.129:18081
      app-id: seata-server
      namespace: application
      apollo-accesskey-secret: ""
  registry:
    # support: nacos, eureka, redis, zk, consul, etcd3, sofa
    type: zk
    zk:
      server-addr: 192.168.3.129:2181,192.168.3.129:2182,192.168.3.129:2183
